version: '2'
services:
  # mysql 服务
  mysql-laravel:
    image: mysql:5.7.17
    environment:
      MYSQL_ROOT_PASSWORD: "123456"
      MYSQL_DATABASE: "laravel"
      MYSQL_USER: "cjw"
      MYSQL_PASSWORD: "123456"
    ports:
      - "33061:3306"
    volumes:
      - mysql-laravel:/var/lib/mysql

  # redis 服务
  redis:
    image: redis:3.2.7
    ports:
      - "6379:6379"
    volumes:
      - redis:/data

  # nginx 服务器: 对外提供80端口
  nginx:
    build: ./nginx/
    ports:
      - "80:80"
      - "443:443"

  php5.6-fpm:
    build: ./php5.6-fpm/
    volumes:
      - php5.6-fpm:/etc/php/5.6
      - ./var/www/php5.6/:/var/www/php5.6

  php7.0-fpm:
    build: ./php7.0-fpm/
    volumes:
      - php7.0-fpm:/etc/php/7.0
      - ./var/www/php7.0/:/var/www/php7.0

  php7.1-fpm:
    build: ./php7.1-fpm/
    volumes:
      - php7.1-fpm:/etc/php/7.1
      - ./var/www/php7.1/:/var/www/php7.1

  apache-php:
    build: ./apache-php/
    volumes:
      - apache-php-config:/etc/php/7.1/
      - ./var/www/apache2/:/var/www/apache2

volumes:
  # apache的匿名数据卷
  mysql-laravel:
    driver: local
  redis:
    driver: local

  php5.6-fpm:
    driver: local
  php7.0-fpm:
    driver: local
  php7.1-fpm:
    driver: local
  apache-php-config:
    driver: local